import type { Project, TeamMember, Task, BurndownPoint, FinancialData, Oportunidad } from "@/types";

export const oportunidades: Oportunidad[] = [
  { id: "op-1",  numero: 24473, encargado: "Max Arancibia",    probabilidad: 20,  estadoProtec: "REUNIÓN CON CLIENTE JUEVES 19 FEB. BAJA PROBABILIDAD DEBIDO A LA PREFERENCIA DEL CLIENTE DE UN DESARROLLADOR LOCAL.", titulo: "[BIS] FP Total Energies - SII USA",                                    businessManager: "Matthieu LEMAITRE", modelo: "Workpackage",     cliente: "Total Energies" },
  { id: "op-2",  numero: 24455, encargado: "Max Arancibia",    probabilidad: 100, estadoProtec: "ENTREGADA x PIO",   titulo: "Modernización Acelerada CONTEXT-AWARE ENGINEERING",                    businessManager: "Enzo LOYOLA",       modelo: "Fixed Price",     cliente: "TRANSBANK" },
  { id: "op-3",  numero: 24444, encargado: "Max Arancibia",    probabilidad: 50,  estadoProtec: "PENDIENTE OPS",     titulo: "[BIS] Licitación Lic ID-3803, Esval S.A",                              businessManager: "Marilyn DELGADO",   modelo: "Fixed Price",     cliente: "ESVAL" },
  { id: "op-4",  numero: 24422, encargado: "JUAN RAMIREZ",     probabilidad: 5,   estadoProtec: "PENDIENTE INFO CLIENTE", titulo: "[BIS] Assessment de PROCESOS se debe hacer una propuesta de Consultora", businessManager: "Marilyn DELGADO",   modelo: "Fixed Price",     cliente: "Banco Estado" },
  { id: "op-5",  numero: 24424, encargado: "JUAN RAMIREZ",     probabilidad: 80,  estadoProtec: "INFORMACIÓN ENTREGADA POR EL CLIENTE, PROPUESTA EN CURSO.", titulo: "Proyecto L'Oréal",            businessManager: "Javiera Miranda",   modelo: "Fixed Price",     cliente: "LOREAL" },
  { id: "op-6",  numero: 24381, encargado: "JUAN RAMIREZ",     probabilidad: 30,  estadoProtec: "PENDIENTE INFO CLIENTE", titulo: "Pagina WEB",                                                       businessManager: "Isidora PROBOSTE",  modelo: "Fixed Price",     cliente: "SDI" },
  { id: "op-7",  numero: 24372, encargado: "JAVIER SERRANO",   probabilidad: 10,  estadoProtec: "PENDIENTE INFO CLIENTE", titulo: "[BIS] Proyecto cálculo tarifas - Grupo Saesa",                     businessManager: "Carla FIGUEROA",    modelo: "Fixed Price",     cliente: "SAESA" },
  { id: "op-8",  numero: 24371, encargado: "FABRICA IA",       probabilidad: 10,  estadoProtec: "PENDIENTE INFO CLIENTE", titulo: "[BIS] Automatización Cartas - Grupo Saesa (PUEDE SER SOLUCION)",   businessManager: "Carla FIGUEROA",    modelo: "Fixed Price",     cliente: "SAESA" },
  { id: "op-9",  numero: 24363, encargado: "JAVIER SERRANO",   probabilidad: 10,  estadoProtec: "PENDIENTE INFO CLIENTE", titulo: "[BIS] Fixed Price - Proyecto 160 KM",                              businessManager: "Yeriel ABDALA",     modelo: "Fixed Price",     cliente: "Aguas del Sol" },
  { id: "op-10", numero: 24196, encargado: "JAVIER SERRANO",   probabilidad: 70,  estadoProtec: "ENTREGADA x PIO",   titulo: "Auditoría Ciberseguridad",                                             businessManager: "Javiera Miranda",   modelo: "Fixed Price",     cliente: "RFP Logística" },
  { id: "op-11", numero: 24379, encargado: "FRANCISCO GARCIA", probabilidad: 50,  estadoProtec: "ENTREGADA x OPS",   titulo: "SMU - Licitación Desarrollo mobile",                                   businessManager: "Jose PINTO",        modelo: "Workpackage",     cliente: "SMU" },
  { id: "op-12", numero: 24338, encargado: "JAVIER SERRANO",   probabilidad: 0,   estadoProtec: "PERDIDO",           titulo: "[BIS] Proyecto RPA - Stock NEWREST",                                   businessManager: "Matthieu LEMAITRE", modelo: "Fixed Price",     cliente: "Newrest" },
  { id: "op-13", numero: 24314, encargado: "JAVIER SERRANO",   probabilidad: 70,  estadoProtec: "ENTREGADA x PIO",   titulo: "[BIS] Soporte Bolsa Horas BD",                                         businessManager: "Carla FIGUEROA",    modelo: "Fixed Price",     cliente: "Brightstar Lottery (Sencillito)" },
  { id: "op-14", numero: 24313, encargado: "JAVIER SERRANO",   probabilidad: 70,  estadoProtec: "ENTREGADA x PIO",   titulo: "[BIS] Assessment Salesforce",                                          businessManager: "Carla FIGUEROA",    modelo: "Fixed Price",     cliente: "Brightstar Lottery (Sencillito)" },
  { id: "op-15", numero: 24253, encargado: "JAVIER SERRANO",   probabilidad: 20,  estadoProtec: "ENTREGADA x PIO",   titulo: "Sistema de Gestión de Procesos y Documentos Normativos",               businessManager: "Lukas NEGRETE",     modelo: "Fixed Price",     cliente: "Transelec" },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Rediseño Portal Cliente",
    status: "active",
    progress: 68,
    budget: 120000,
    spent: 81600,
    revenue: 150000,
    startDate: "2025-11-01",
    endDate: "2026-03-31",
    teamSize: 5,
    tasksTotal: 42,
    tasksDone: 29,
    manager: "Ana García",
  },
  {
    id: "p2",
    name: "Migración Cloud AWS",
    status: "at-risk",
    progress: 44,
    budget: 200000,
    spent: 132000,
    revenue: 240000,
    startDate: "2025-09-15",
    endDate: "2026-02-28",
    teamSize: 8,
    tasksTotal: 75,
    tasksDone: 33,
    manager: "Carlos Méndez",
  },
  {
    id: "p3",
    name: "App Mobile iOS/Android",
    status: "active",
    progress: 82,
    budget: 90000,
    spent: 73800,
    revenue: 115000,
    startDate: "2025-08-01",
    endDate: "2026-01-31",
    teamSize: 4,
    tasksTotal: 58,
    tasksDone: 48,
    manager: "Laura Pérez",
  },
  {
    id: "p4",
    name: "BI & Analytics Dashboard",
    status: "completed",
    progress: 100,
    budget: 60000,
    spent: 57200,
    revenue: 80000,
    startDate: "2025-06-01",
    endDate: "2025-12-15",
    teamSize: 3,
    tasksTotal: 30,
    tasksDone: 30,
    manager: "Pedro Ruiz",
  },
  {
    id: "p5",
    name: "Integración ERP SAP",
    status: "on-hold",
    progress: 25,
    budget: 180000,
    spent: 45000,
    revenue: 220000,
    startDate: "2026-01-15",
    endDate: "2026-08-30",
    teamSize: 6,
    tasksTotal: 90,
    tasksDone: 22,
    manager: "Ana García",
  },
];

export const teamMembers: TeamMember[] = [
  { id: "m1", name: "Ana García",    role: "PM",        avatar: "AG", hourlyRate: 85,  hoursWorked: 312, projectsCount: 2, utilization: 78 },
  { id: "m2", name: "Carlos Méndez", role: "Developer", avatar: "CM", hourlyRate: 75,  hoursWorked: 380, projectsCount: 1, utilization: 95 },
  { id: "m3", name: "Laura Pérez",   role: "Designer",  avatar: "LP", hourlyRate: 70,  hoursWorked: 290, projectsCount: 2, utilization: 72 },
  { id: "m4", name: "Pedro Ruiz",    role: "Analyst",   avatar: "PR", hourlyRate: 65,  hoursWorked: 240, projectsCount: 1, utilization: 60 },
  { id: "m5", name: "Sofía Torres",  role: "Developer", avatar: "ST", hourlyRate: 78,  hoursWorked: 400, projectsCount: 2, utilization: 100 },
  { id: "m6", name: "Miguel León",   role: "QA",        avatar: "ML", hourlyRate: 60,  hoursWorked: 260, projectsCount: 3, utilization: 65 },
  { id: "m7", name: "Valeria Cruz",  role: "Developer", avatar: "VC", hourlyRate: 72,  hoursWorked: 350, projectsCount: 1, utilization: 87 },
  { id: "m8", name: "Diego Mora",    role: "PM",        avatar: "DM", hourlyRate: 80,  hoursWorked: 200, projectsCount: 1, utilization: 50 },
];

export const tasks: Task[] = [
  // Proyecto 1
  { id: "t1",  name: "Diseño UX wireframes",        assignee: "Laura Pérez",   status: "done",        priority: "high",     startDate: "2025-11-01", endDate: "2025-11-20", progress: 100, projectId: "p1" },
  { id: "t2",  name: "Desarrollo frontend React",   assignee: "Sofía Torres",  status: "in-progress", priority: "high",     startDate: "2025-11-21", endDate: "2026-02-15", progress: 70,  projectId: "p1" },
  { id: "t3",  name: "API REST backend",            assignee: "Carlos Méndez", status: "in-progress", priority: "critical", startDate: "2025-12-01", endDate: "2026-02-28", progress: 55,  projectId: "p1" },
  { id: "t4",  name: "Testing y QA",                assignee: "Miguel León",   status: "todo",        priority: "medium",   startDate: "2026-02-20", endDate: "2026-03-15", progress: 0,   projectId: "p1" },
  { id: "t5",  name: "Deploy producción",           assignee: "Carlos Méndez", status: "todo",        priority: "high",     startDate: "2026-03-16", endDate: "2026-03-31", progress: 0,   projectId: "p1" },
  // Proyecto 2
  { id: "t6",  name: "Auditoría infraestructura",   assignee: "Pedro Ruiz",    status: "done",        priority: "high",     startDate: "2025-09-15", endDate: "2025-10-15", progress: 100, projectId: "p2" },
  { id: "t7",  name: "Migración base de datos",     assignee: "Valeria Cruz",  status: "blocked",     priority: "critical", startDate: "2025-10-16", endDate: "2025-12-31", progress: 40,  projectId: "p2" },
  { id: "t8",  name: "Configuración VPC y redes",   assignee: "Carlos Méndez", status: "in-progress", priority: "high",     startDate: "2025-11-01", endDate: "2026-01-31", progress: 60,  projectId: "p2" },
  { id: "t9",  name: "Pruebas de carga",            assignee: "Miguel León",   status: "todo",        priority: "medium",   startDate: "2026-02-01", endDate: "2026-02-28", progress: 0,   projectId: "p2" },
  // Proyecto 3
  { id: "t10", name: "Diseño UI mobile",            assignee: "Laura Pérez",   status: "done",        priority: "high",     startDate: "2025-08-01", endDate: "2025-09-15", progress: 100, projectId: "p3" },
  { id: "t11", name: "Desarrollo iOS Swift",        assignee: "Sofía Torres",  status: "done",        priority: "high",     startDate: "2025-09-16", endDate: "2026-01-15", progress: 100, projectId: "p3" },
  { id: "t12", name: "Desarrollo Android Kotlin",   assignee: "Valeria Cruz",  status: "in-progress", priority: "high",     startDate: "2025-09-16", endDate: "2026-01-31", progress: 85,  projectId: "p3" },
  { id: "t13", name: "Publicación App Store",       assignee: "Diego Mora",    status: "todo",        priority: "critical", startDate: "2026-01-20", endDate: "2026-01-31", progress: 10,  projectId: "p3" },
];

export const burndownData: BurndownPoint[] = [
  { day: "Sem 1",  ideal: 100, actual: 100 },
  { day: "Sem 2",  ideal: 88,  actual: 90  },
  { day: "Sem 3",  ideal: 76,  actual: 82  },
  { day: "Sem 4",  ideal: 64,  actual: 71  },
  { day: "Sem 5",  ideal: 52,  actual: 65  },
  { day: "Sem 6",  ideal: 40,  actual: 55  },
  { day: "Sem 7",  ideal: 28,  actual: 48  },
  { day: "Sem 8",  ideal: 16,  actual: 38  },
  { day: "Sem 9",  ideal: 4,   actual: 32  },
  { day: "Sem 10", ideal: 0,   actual: null as unknown as number },
];

export const financialData: FinancialData[] = projects.map((p) => ({
  projectId: p.id,
  revenue: p.revenue,
  directCosts: p.spent * 0.7,
  operatingExpenses: p.spent * 0.3,
  budget: p.budget,
  spent: p.spent,
}));
